services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "4000:4000"
    networks:
      - app-network
    environment:
      - SERVICE_APP_NAME=Fixit Service
      - SERVICE_APP_PORT=4000
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=fixit-service
      - DB_USERNAME=
      - DB_PASSWORD=
      - JWT_SECRET=Fz3!5LF9qIa@G6i*wx@T
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - app-network
    environment:
      - VITE_SERVICE_URL=http://backend:4000
    depends_on:
      - backend

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=fixit-service
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
