import React, { useState, useEffect } from "react";
import {
  Typography,
  Button,
  Box,
  TextField,
  IconButton,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  MenuItem,
  Table,
  TableHead,
  TableBody,
  TableRow,
  TableCell,
  Paper,
  Chip,
} from "@mui/material";
import { Add as AddIcon, Edit as EditIcon, Delete as DeleteIcon } from "@mui/icons-material";
import { format } from "date-fns";
import axios from "axios";
import { jwtDecode } from "jwt-decode";
import DeleteDialog from "../components/DeleteDialog";
import constants from "../utils/constants";

interface User {
  id: string;
  name: string;
}

interface Incident {
  id: number;
  name: string;
  description: string;
  priority: "low" | "medium" | "high" | "critical";
  status: "open" | "inprogress" | "resolved" | "closed";
  date: string; // Date is auto-generated by backend
  reportedBy?: IIncidentUser;
  assignedTo?: IIncidentUser;
}

interface IIncidentUser {
  id: string;
  name: string;
}

interface TokenPayload {
  user: { _id: string };
}

// Priority and Status translations
const priorityMap: Record<string, string> = {
  low: "Baja",
  medium: "Media",
  high: "Alta",
  critical: "Crítica",
};

const statusMap: Record<string, string> = {
  open: "Abierto",
  inprogress: "En progreso",
  resolved: "Resuelto",
  closed: "Cerrado",
};

const Dashboard: React.FC = () => {
  const [incidents, setIncidents] = useState<Incident[]>([]);
  const [filteredIncidents, setFilteredIncidents] = useState<Incident[]>([]);
  const [users, setUsers] = useState<User[]>([]);
  const [search, setSearch] = useState<string>("");

  // State for Modals
  const [openModal, setOpenModal] = useState<boolean>(false);
  const [editModal, setEditModal] = useState<boolean>(false);
  const [deleteDialog, setDeleteDialog] = useState<boolean>(false);
  const [selectedIncident, setSelectedIncident] = useState<Incident | null>(null);

  const [formData, setFormData] = useState<Omit<Incident, "id" | "date">>({
    name: "",
    description: "",
    priority: "low",
    status: "open",
  });

  const [userId, setUserId] = useState<string>("");

  const token = localStorage.getItem("token") || sessionStorage.getItem("token");

  // Decode user ID from token
  useEffect(() => {
    if (token) {
      const decoded = jwtDecode<TokenPayload>(token);
      setUserId(decoded.user._id);
    }
    fetchUsers();
    fetchIncidents();
  }, []);

  // Fetch users
  const fetchUsers = async () => {
    try {
      const response = await axios.get(`${constants.SERVICE_URL}/user/`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      setUsers(response.data);
    } catch (error) {
      console.error("Error fetching users:", error);
    }
  };

  // Fetch incidents
  const fetchIncidents = async () => {
    try {
      const response = await axios.get(`${constants.SERVICE_URL}/incidence`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      setIncidents(response.data);
      setFilteredIncidents(response.data);
    } catch (error) {
      console.error("Error fetching incidents:", error);
    }
  };

  // Search functionality
  useEffect(() => {
    const filtered = incidents.filter((incident) => incident.name.toLowerCase().includes(search.toLowerCase()));
    setFilteredIncidents(filtered);
  }, [search, incidents]);

  // Submit Create/Edit
  const handleSubmit = async () => {
    try {
      const data = {
        ...formData,
        reportedBy: userId,
        assignedTo: formData.assignedTo || undefined,
      };

      if (editModal && selectedIncident) {
        await axios.put(`${constants.SERVICE_URL}/incidence/${selectedIncident.id}`, data, {
          headers: { Authorization: `Bearer ${token}` },
        });
      } else {
        await axios.post(`${constants.SERVICE_URL}/incidence`, data, {
          headers: { Authorization: `Bearer ${token}` },
        });
      }

      fetchIncidents();
      handleCloseModals();
    } catch (error) {
      console.error("Error saving incident:", error);
    }
  };

  // Delete Incident
  const handleDelete = async () => {
    try {
      if (selectedIncident) {
        await axios.delete(`${constants.SERVICE_URL}/incidence/${selectedIncident.id}`, {
          headers: { Authorization: `Bearer ${token}` },
        });
        fetchIncidents();
      }
      setDeleteDialog(false);
    } catch (error) {
      console.error("Error deleting incident:", error);
    }
  };

  const handleOpenEdit = (incident: Incident) => {
    setSelectedIncident(incident);
    setFormData({
      name: incident.name,
      description: incident.description,
      priority: incident.priority,
      status: incident.status,
      reportedBy: incident.reportedBy,
      assignedTo: incident.assignedTo || undefined,
    });
    setEditModal(true);
  };

  const handleCloseModals = () => {
    setOpenModal(false);
    setEditModal(false);
    setDeleteDialog(false);
    setSelectedIncident(null);
    setFormData({
      name: "",
      description: "",
      priority: "low",
      status: "open",
    });
  };

  const openDeleteDialog = (incident: Incident) => {
    setSelectedIncident(incident);
    setDeleteDialog(true);
  };

  const getChipColor = (value: string) => {
    switch (value) {
      case "low":
      case "open":
        return "success";
      case "medium":
      case "inprogress":
        return "warning";
      case "high":
      case "critical":
        return "error";
      case "resolved":
      case "closed":
        return "default";
      default:
        return "default";
    }
  };

  return (
    <Box sx={{ flexGrow: 1, p: 3 }}>
      <Typography variant="h4" gutterBottom>
        Incidentes
      </Typography>

      <Box sx={{ display: "flex", justifyContent: "space-between", mb: 2 }}>
        <TextField label="Buscar por nombre" variant="outlined" size="small" value={search} onChange={(e) => setSearch(e.target.value)} />
        <Button variant="contained" color="primary" startIcon={<AddIcon />} onClick={() => setOpenModal(true)}>
          Crear Incidente
        </Button>
      </Box>

      <Paper>
        <Table>
          <TableHead>
            <TableRow>
              <TableCell>Nombre</TableCell>
              <TableCell>Descripción</TableCell>
              <TableCell>Prioridad</TableCell>
              <TableCell>Estado</TableCell>
              <TableCell>Reportado Por</TableCell>
              <TableCell>Asignado A</TableCell>
              <TableCell>Fecha</TableCell>
              <TableCell>Acciones</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {filteredIncidents.map((incident) => (
              <TableRow key={incident.id}>
                <TableCell>{incident.name}</TableCell>
                <TableCell>{incident.description}</TableCell>
                <TableCell>
                  <Chip label={priorityMap[incident.priority]} color={getChipColor(incident.priority)} />
                </TableCell>
                <TableCell>
                  <Chip label={statusMap[incident.status]} color={getChipColor(incident.status)} />
                </TableCell>
                <TableCell>{incident.reportedBy?.name}</TableCell>
                <TableCell>{incident.assignedTo?.name || "N/A"}</TableCell>
                <TableCell>{format(new Date(incident.date), "yyyy-MM-dd")}</TableCell>
                <TableCell>
                  <IconButton color="primary" onClick={() => handleOpenEdit(incident)}>
                    <EditIcon />
                  </IconButton>
                  <IconButton color="error" onClick={() => openDeleteDialog(incident)}>
                    <DeleteIcon />
                  </IconButton>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </Paper>

      <Dialog open={openModal || editModal} onClose={handleCloseModals}>
        <DialogTitle>{editModal ? "Editar Incidente" : "Crear Incidente"}</DialogTitle>
        <DialogContent>
          <TextField
            fullWidth
            label="Nombre"
            value={formData.name}
            onChange={(e) => setFormData({ ...formData, name: e.target.value })}
            margin="normal"
          />
          <TextField
            fullWidth
            label="Descripción"
            value={formData.description}
            onChange={(e) => setFormData({ ...formData, description: e.target.value })}
            margin="normal"
          />
          <TextField
            select
            fullWidth
            label="Prioridad"
            value={formData.priority}
            onChange={(e) => setFormData({ ...formData, priority: e.target.value as Incident["priority"] })}
            margin="normal"
          >
            {Object.entries(priorityMap).map(([key, value]) => (
              <MenuItem key={key} value={key}>
                {value}
              </MenuItem>
            ))}
          </TextField>
          <TextField
            select
            fullWidth
            label="Estado"
            value={formData.status}
            onChange={(e) => setFormData({ ...formData, status: e.target.value as Incident["status"] })}
            margin="normal"
          >
            {Object.entries(statusMap).map(([key, value]) => (
              <MenuItem key={key} value={key}>
                {value}
              </MenuItem>
            ))}
          </TextField>
          <TextField
            select
            fullWidth
            label="Asignado A"
            value={formData.assignedTo?.id || undefined}
            onChange={(e) =>
              setFormData({
                ...formData,
                assignedTo: { id: e.target.value, name: users.find((user) => user.id === e.target.value)?.name || "" },
              })
            }
            margin="normal"
          >
            {users.map((user) => (
              <MenuItem key={user.id} value={user.id}>
                {user.name}
              </MenuItem>
            ))}
          </TextField>
        </DialogContent>
        <DialogActions>
          <Button onClick={handleCloseModals}>Cancelar</Button>
          <Button onClick={handleSubmit} color="primary">
            Guardar
          </Button>
        </DialogActions>
      </Dialog>

      <DeleteDialog
        open={deleteDialog}
        title="Eliminar Incidente"
        message={`¿Estás seguro de que deseas eliminar el incidente "${selectedIncident?.name}"?`}
        onClose={() => setDeleteDialog(false)}
        onConfirm={handleDelete}
      />
    </Box>
  );
};

export default Dashboard;
